// Auto-generated by `supabase gen types typescript`. Do not edit by hand.
// Regenerate with the Supabase MCP after schema changes (or `supabase gen types
// typescript --project-id kxmthvesycgcgevlpqvi --schema public`).

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
	// Allows to automatically instantiate createClient with right options
	// instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
	__InternalSupabase: {
		PostgrestVersion: '14.5';
	};
	public: {
		Tables: {
			[_ in never]: never;
		};
		Views: {
			etl_last_updated: {
				Row: {
					finished_at: string | null;
				};
				Relationships: [];
			};
			fixtures: {
				Row: {
					code: number | null;
					finished: boolean | null;
					finished_provisional: boolean | null;
					gameweek_id: number | null;
					id: number | null;
					kickoff_time: string | null;
					minutes: number | null;
					provisional_start_time: boolean | null;
					pulse_id: number | null;
					started: boolean | null;
					stats: Json | null;
					team_a_difficulty: number | null;
					team_a_id: number | null;
					team_a_score: number | null;
					team_h_difficulty: number | null;
					team_h_id: number | null;
					team_h_score: number | null;
				};
				Relationships: [];
			};
			gameweeks: {
				Row: {
					average_entry_score: number | null;
					can_enter: boolean | null;
					can_manage: boolean | null;
					chip_plays: Json | null;
					cup_leagues_created: boolean | null;
					data_checked: boolean | null;
					deadline_time: string | null;
					deadline_time_epoch: number | null;
					deadline_time_game_offset: number | null;
					finished: boolean | null;
					h2h_ko_matches_created: boolean | null;
					highest_score: number | null;
					highest_scoring_entry: number | null;
					id: number | null;
					is_current: boolean | null;
					is_next: boolean | null;
					is_previous: boolean | null;
					most_captained: number | null;
					most_selected: number | null;
					most_transferred_in: number | null;
					most_vice_captained: number | null;
					name: string | null;
					overrides: Json | null;
					ranked_count: number | null;
					release_time: string | null;
					released: boolean | null;
					top_element: number | null;
					top_element_info: Json | null;
					transfers_made: number | null;
				};
				Relationships: [];
			};
			teams: {
				Row: {
					code: number | null;
					draw: number | null;
					form: string | null;
					id: number | null;
					loss: number | null;
					name: string | null;
					played: number | null;
					points: number | null;
					position: number | null;
					pulse_id: number | null;
					short_name: string | null;
					strength: number | null;
					strength_attack_away: number | null;
					strength_attack_home: number | null;
					strength_defence_away: number | null;
					strength_defence_home: number | null;
					strength_overall_away: number | null;
					strength_overall_home: number | null;
					team_division: string | null;
					unavailable: boolean | null;
					win: number | null;
				};
				Relationships: [];
			};
		};
		Functions: {
			player_history: {
				Args: { p_player_id: number };
				Returns: {
					assists: number;
					away_score: number;
					bonus: number;
					bps: number;
					creativity: number;
					cs: number;
					defensive_contribution: number;
					gameweek_id: number;
					goals_conceded: number;
					goals_scored: number;
					home_score: number;
					ict_index: number;
					influence: number;
					minutes: number;
					opponent: string;
					opponent_code: number;
					own_goals: number;
					penalties_missed: number;
					penalties_saved: number;
					pts: number;
					red_cards: number;
					saves: number;
					starts: number;
					threat: number;
					was_home: boolean;
					xa: number;
					xg: number;
					xgc: number;
					xgi: number;
					xpts: number;
					yellow_cards: number;
				}[];
			};
			player_stats: {
				Args: {
					gw_from?: number;
					gw_to?: number;
					include_current?: boolean;
					last_n?: number;
				};
				Returns: {
					a: number;
					a90: number;
					appearance_pp90: number;
					assists_pp90: number;
					bonus_pp90: number;
					cs: number;
					deductions_pp90: number;
					defensive_pp90: number;
					gi: number;
					gi90: number;
					goals_pp90: number;
					gp: number;
					gs: number;
					gs90: number;
					mp: number;
					mp_pct: number;
					p90: number;
					player: string;
					player_id: number;
					pos: string;
					ppg: number;
					price: number;
					pts: number;
					saves_pp90: number;
					st: number;
					team: string;
					team_code: number;
					tsb: number;
					xa90: number;
					xg90: number;
					xgc: number;
					xgc90: number;
					xgi90: number;
					xp90: number;
					xppg: number;
				}[];
			};
		};
		Enums: {
			[_ in never]: never;
		};
		CompositeTypes: {
			[_ in never]: never;
		};
	};
};
